DROP DATABASE IF EXISTS fooddelivery;
CREATE DATABASE fooddelivery;
USE fooddelivery;

CREATE TABLE COMUNE (
    IDcomune INT (4) UNSIGNED ZEROFILL AUTO_INCREMENT PRIMARY KEY NOT NULL,
    nome VARCHAR(50) NOT NULL    
);

CREATE TABLE CLIENTE (
    Email VARCHAR(50) NOT NULL PRIMARY KEY,
    nTel VARCHAR(18) NOT NULL,
    nome VARCHAR(50) NOT NULL,
    cognome VARCHAR(50) NOT NULL,
    ind_fatt_via VARCHAR (30) NOT NULL,
	ind_fatt_civ VARCHAR (30) NOT NULL,
    ind_fatt_cap INT (5) NOT NULL,
    ind_fatt_comune VARCHAR (30) NOT NULL,

    password VARCHAR(64) NOT NULL,
    salt VARCHAR(64) NOT NULL,
	
	FK_IDcomune INT (4) UNSIGNED ZEROFILL  NOT NULL,
	
	UNIQUE(nTel),
	
	FOREIGN KEY (FK_IDcomune) REFERENCES COMUNE(IDcomune)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    CHECK (Email LIKE '%@%')
);

CREATE TABLE INDIRIZZO (
    IDindirizzo INT (6) UNSIGNED ZEROFILL AUTO_INCREMENT PRIMARY KEY  NOT NULL,
	ind_via VARCHAR (30) NOT NULL,
    ind_civ VARCHAR (30) NOT NULL,
    ind_cap INT (5) NOT NULL,
    ind_comune VARCHAR (30) NOT NULL,
	
    FK_Email VARCHAR(50)  NOT NULL,
    FK_IDcomune INT (4) UNSIGNED ZEROFILL  NOT NULL,
   FOREIGN KEY (FK_Email) REFERENCES CLIENTE(Email)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (FK_IDcomune) REFERENCES COMUNE(IDcomune)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);


CREATE TABLE ORDINE (
    IDordine INT (6) UNSIGNED ZEROFILL AUTO_INCREMENT PRIMARY KEY  NOT NULL,
    stato ENUM('ricevuto', 'in preparazione', 'in consegna', 'consegnato')  NOT NULL,
    FKEmail VARCHAR(50)  NOT NULL,
    FKIDindirizzo INT (6) UNSIGNED ZEROFILL  NOT NULL,
	FKRider VARCHAR(16) NULL, -- null se non è ancora stato preso in carico
	FK_IDmetodo INT (2) UNSIGNED ZEROFILL  NOT NULL,
    FOREIGN KEY (FKEmail) REFERENCES CLIENTE(Email)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (FKIDindirizzo) REFERENCES INDIRIZZO(IDindirizzo)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);


CREATE TABLE RIDER (
    CF VARCHAR(16) PRIMARY KEY NOT NULL,
    nome VARCHAR(50) NOT NULL,
    cognome VARCHAR(50) NOT NULL,
    iban VARCHAR(27) NOT NULL
);


CREATE TABLE ZONA (
    IDzona INT (2) UNSIGNED ZEROFILL AUTO_INCREMENT PRIMARY KEY  NOT NULL,
	NomeZona VARCHAR(30) NOT NULL
);


CREATE TABLE ORARI_APERTURE (
    IDgiorno INT (1) UNSIGNED NOT NULL,
    FKIDristorante INT (2) UNSIGNED ZEROFILL NOT NULL,
    orarioApertura TIME NOT NULL,
    orarioChiusura TIME NOT NULL,

    PRIMARY KEY (IDgiorno, FKIDristorante),

    CHECK (orarioApertura < orarioChiusura),
    CHECK (IDgiorno < 7) -- 0=domenica, 1=lunedì, etc
);


CREATE TABLE RISTORANTE (
    IDristorante INT (2) UNSIGNED ZEROFILL AUTO_INCREMENT PRIMARY KEY  NOT NULL,
    nome VARCHAR(50) NOT NULL,
    nTel VARCHAR(18) NOT NULL,
    ind_fatt_via VARCHAR (30) NOT NULL,
	ind_fatt_civ VARCHAR (30) NOT NULL,
    ind_fatt_cap INT (5) NOT NULL,
    ind_fatt_comune VARCHAR (30) NOT NULL,
    img VARCHAR(255) NOT NULL,
    descrizione VARCHAR(200) NOT NULL,
	
	FK_IDcomune INT (4) UNSIGNED ZEROFILL  NOT NULL,
	
	UNIQUE(nTel),
	
	FOREIGN KEY (FK_IDcomune) REFERENCES COMUNE(IDcomune)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
	
);

CREATE TABLE PIATTO (
    nome VARCHAR(30) NOT NULL,
    IDpiatto INT (4) UNSIGNED ZEROFILL AUTO_INCREMENT PRIMARY KEY  NOT NULL,
    prezzo DECIMAL(5,2) UNSIGNED NOT NULL, -- max 999,99
    disponibilita BOOLEAN NOT NULL,
    FK_IDristorante INT (2) UNSIGNED ZEROFILL,
    FOREIGN KEY (FK_IDristorante) REFERENCES RISTORANTE(IDristorante)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


CREATE TABLE INGREDIENTE (
    IDingrediente INT (3) UNSIGNED ZEROFILL AUTO_INCREMENT PRIMARY KEY  NOT NULL,
    nome VARCHAR(50) NOT NULL
);


CREATE TABLE ALLERGENE (
    IDallergene INT (2) UNSIGNED ZEROFILL AUTO_INCREMENT PRIMARY KEY  NOT NULL,
    nome VARCHAR(50) NOT NULL,
    personalizzazioni VARCHAR(100) NOT NULL
);

CREATE TABLE CARTA (
    Ncarta INT(16) UNSIGNED ZEROFILL AUTO_INCREMENT PRIMARY KEY NOT NULL,
	CodiceRetro INT(4) NOT NULL,
    banca VARCHAR(50) NOT NULL,
	FKEmail VARCHAR(50)  NOT NULL,
	
    FOREIGN KEY (FKEmail) REFERENCES CLIENTE(Email)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE RECENSIONE (
    IDrecensione INT (2) UNSIGNED ZEROFILL AUTO_INCREMENT PRIMARY KEY  NOT NULL,
    descrizione VARCHAR(200) NOT NULL,
    stelle INT (1) NOT NULL,
    FK_IDordine INT (2) UNSIGNED ZEROFILL  NOT NULL,
    CHECK (stelle BETWEEN 1 AND 5),
    FOREIGN KEY (FK_IDordine) REFERENCES ORDINE(IDordine)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


CREATE TABLE PROMOZIONE (
    IDpromozione INT (2) UNSIGNED ZEROFILL AUTO_INCREMENT PRIMARY KEY  NOT NULL,
    dataInizio DATE NOT NULL,
    dataFine DATE NOT NULL,
    nome VARCHAR(50) NOT NULL,
     CHECK (dataInizio <= dataFine)
);

CREATE TABLE RIDER_ZONA (
    FK_CF VARCHAR(16) NOT NULL,
    FK_IDzona INT (2) UNSIGNED ZEROFILL  NOT NULL,
    PRIMARY KEY (FK_CF, FK_IDzona),
     FOREIGN KEY (FK_CF) REFERENCES RIDER(CF)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (FK_IDzona) REFERENCES ZONA(IDzona)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


CREATE TABLE ZONA_COMUNE (
    FK_IDzona INT (2) UNSIGNED ZEROFILL  NOT NULL,
    FK_IDcomune INT (4) UNSIGNED ZEROFILL  NOT NULL,
    PRIMARY KEY (FK_IDzona, FK_IDcomune),
    FOREIGN KEY (FK_IDzona) REFERENCES ZONA(IDzona)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (FK_IDcomune) REFERENCES COMUNE(IDcomune)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


CREATE TABLE ORDINE_PROMOZIONE (
    FK_IDordine INT (2) UNSIGNED ZEROFILL  NOT NULL,
    FK_IDpromozione INT (2) UNSIGNED ZEROFILL  NOT NULL,
    PRIMARY KEY (FK_IDordine, FK_IDpromozione),
     FOREIGN KEY (FK_IDordine) REFERENCES ORDINE(IDordine)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (FK_IDpromozione) REFERENCES PROMOZIONE(IDpromozione)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


CREATE TABLE PROMOZIONE_PIATTO (
    FK_IDpromozione INT (2) UNSIGNED ZEROFILL  NOT NULL,
    FK_IDpiatto INT (2) UNSIGNED ZEROFILL  NOT NULL,
    PRIMARY KEY (FK_IDpromozione, FK_IDpiatto),
    FOREIGN KEY (FK_IDpromozione) REFERENCES PROMOZIONE(IDpromozione)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (FK_IDpiatto) REFERENCES PIATTO(IDpiatto)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


CREATE TABLE PIATTO_ORDINE (
    FK_IDpiatto INT (2) UNSIGNED ZEROFILL  NOT NULL,
    FK_IDordine INT (2) UNSIGNED ZEROFILL  NOT NULL,
    PRIMARY KEY (FK_IDpiatto, FK_IDordine),
    FOREIGN KEY (FK_IDpiatto) REFERENCES PIATTO(IDpiatto)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (FK_IDordine) REFERENCES ORDINE(IDordine)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


CREATE TABLE INGREDIENTE_PIATTO (
    FK_IDingrediente INT (3) UNSIGNED ZEROFILL  NOT NULL,
    FK_IDpiatto INT (4) UNSIGNED ZEROFILL  NOT NULL,
	quantita int (2) NULL,
    PRIMARY KEY (FK_IDingrediente, FK_IDpiatto),
    FOREIGN KEY (FK_IDingrediente) REFERENCES INGREDIENTE(IDingrediente)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (FK_IDpiatto) REFERENCES PIATTO(IDpiatto)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


CREATE TABLE INGREDIENTE_ALLERGENE (
    FK_IDingrediente INT (2) UNSIGNED ZEROFILL  NOT NULL,
    FK_IDallergene INT (2) UNSIGNED ZEROFILL  NOT NULL,
    PRIMARY KEY (FK_IDingrediente, FK_IDallergene),
    FOREIGN KEY (FK_IDingrediente) REFERENCES INGREDIENTE(IDingrediente)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (FK_IDallergene) REFERENCES ALLERGENE(IDallergene)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

COMMIT;